### Global Variables
@baseUrl = https://localhost:8080
@username = johndoe
@password = johndoe208
@email = johndoe@gmail.com

### Register a new user
# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
    "userName": "{{username}}",
    "password": "{{password}}",
    "mail": "{{email}}"
}

### Login
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "password": "{{password}}",
    "email": "{{email}}"
}
