### 1. Register a new user
POST https://localhost:8080/register
Content-Type: application/json

{
  "userName": "johndoe",
  "mail": "john@example.com",
  "password": "SecurePassword123"
}

### 2. Login to get JWT
# @name login
POST https://localhost:8080/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "SecurePassword123"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2YjBmNmQzLTcyYjEtNDNmNi05MjAxLTNlMjgwOGM5NjMzNSIsInVzZXJOIjoiam9obmRvZSIsImlhdCI6MTc3NzYzNDkyNywiZXhwIjoxNzc3NjM4NTI3fQ.n6mHJZ4GGrpZ7uCHP4T3hhBch9EYnOp2bvcq-QgCMS8
### 3. Add a book to user's collection

POST https://localhost:8080/b6b0f6d3-72b1-43f6-9201-3e2808c96335/book/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald"
}